- NameplateFilter.lua
Since hunters can name their pets Psyfiend, etc. for any unit name without spaces, prefer to use NPC ID for the whitelist.
To find the NPC ID of a certain unit, target it and type:
`/run npcID = select(6, strsplit("-", UnitGUID("target"))); print(npcID);`
> Use Npc ID for nameplate filter whitelist for unit names with no spaces

- SpellData.lua
- UnitInfoHelpers.lua
- UtilsWA.lua
Support Gladius anchoring for defensive cooldowns
> Remove dead code

- SpellData.lua
- UnitInfoHelpers.lua
- UtilsWA.lua
tracking unit is not reliable, reverting the previous change.
> fix shambling rush

- NameplateFilter.lua
Inside arena, scale indicator to 3, and show class icon on top;
otherwise, use default options
> Update indicator anchor based on instance

- NameplateFilter.lua
Uncheck "Icon Customization Enabled":
> Always show regular cast bar

- Personalization.lua
- UnitInfoHelpers.lua
- Update function to find raid style party frames
- Update code to sort party by "party1" - "player" - "party2"
> Update for DF pre-patch

- Personalization.lua
Still blocked when leaving edit mode, but seems fine otherwise so far
> Fix sort group

- NameplateFilter.lua
> Fix hunter pet nameplate filtering

- Internal/SortGroup.lua
Leverage widget API SetPoint to adjust raid frame positions, shouldn't taint anything.
> Another attempt to fix sortgroup

- ClassAndPetIcons.lua
fel obelisk is important to kill and tyrant is important to at least know the location of
> add other demo lock pets

- ArenaFrames/ArenaEnemyBurst.lua
- ArenaFrames/CooldownTracking.lua
- Core.lua
> Support Blizzard arena frames

- Core.lua
> Show message on first 3 runs of the addon

- Core.lua
- Misc/HealerInCrowdControl.lua
> Polish healer in cc display

- Common/UnitInfoHelpers.lua
- Core.lua
- Misc/HealerInCrowdControl.lua
- Misc/QueueReminder.lua
- Nameplates/SpecIcons.lua
Show all enemy players:
Show enemy healers only:
> Battleground spec / healer icons

- Common/Constants.lua
- Nameplates/SpecIcons.lua
> Enemy healers show a red healer icon

- Common/Constants.lua
- Nameplates/ClassIcons.lua
> Fc icon neutral

- Core.lua
- Docs/Todo.md
- RaidFrames/FixBlizzardRaidAggro.lua
Optimize the logic to reduce # checks.
Also make it possible to support other frames, such as ElvUI
> Refactor raidframe aggro

- Nameplates/SpecIcons.lua
> Optimize spec icon, call ClearPoints to update alignment instead of creating 3 icons

- ArenaFrames/ArenaCooldowns.lua
- ArenaFrames/ArenaEnemyBurstTemplates.lua
- ArenaFrames/CooldownTrackingTemplates.lua
- ArenaFrames/IconGroupUtil.lua
- Common/ArenaEnemyUtilitySpells.lua
- Common/Constants.lua
- Common/SpellData.lua
- Core.lua
- SweepyBoop.toc
- Option to consolidate all abilities into one row
- Option to customize icon flow direction
> Refactor cd tracker

- Common/SpellData.lua
Added for MW only since they can port in stuns
Consider adding an option to filter by spec
> Add mw port
